/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as MarketingBrandingRouteImport } from './routes/_marketing/branding'
import { Route as MarketingWaitlistConfirmedRouteImport } from './routes/_marketing/waitlist.confirmed'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBrandingRoute = MarketingBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingWaitlistConfirmedRoute =
  MarketingWaitlistConfirmedRouteImport.update({
    id: '/waitlist/confirmed',
    path: '/waitlist/confirmed',
    getParentRoute: () => MarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/branding': typeof MarketingBrandingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/waitlist/confirmed': typeof MarketingWaitlistConfirmedRoute
}
export interface FileRoutesByTo {
  '/docs': typeof DocsRouteWithChildren
  '/branding': typeof MarketingBrandingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/': typeof MarketingIndexRoute
  '/waitlist/confirmed': typeof MarketingWaitlistConfirmedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/_marketing/branding': typeof MarketingBrandingRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/waitlist/confirmed': typeof MarketingWaitlistConfirmedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/branding'
    | '/privacy'
    | '/terms'
    | '/docs/$slug'
    | '/waitlist/confirmed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docs'
    | '/branding'
    | '/privacy'
    | '/terms'
    | '/docs/$slug'
    | '/'
    | '/waitlist/confirmed'
  id:
    | '__root__'
    | '/_marketing'
    | '/docs'
    | '/_marketing/branding'
    | '/_marketing/privacy'
    | '/_marketing/terms'
    | '/docs/$slug'
    | '/_marketing/'
    | '/_marketing/waitlist/confirmed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/branding': {
      id: '/_marketing/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof MarketingBrandingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/waitlist/confirmed': {
      id: '/_marketing/waitlist/confirmed'
      path: '/waitlist/confirmed'
      fullPath: '/waitlist/confirmed'
      preLoaderRoute: typeof MarketingWaitlistConfirmedRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingBrandingRoute: typeof MarketingBrandingRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingWaitlistConfirmedRoute: typeof MarketingWaitlistConfirmedRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingBrandingRoute: MarketingBrandingRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingWaitlistConfirmedRoute: MarketingWaitlistConfirmedRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
